[general]
live_config_reload = true

[colors.primary]
background = '#000000'
foreground = '#d3d7cf'

[colors.normal]
black = '#2e3436'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#dbded8'

[colors.bright]
black = '#555753'
red = '#ef2929'
green = '#8ae234'
yellow = '#fce94f'
blue = '#729fcf'
magenta = '#ad7fa8'
cyan = '#34e2e2'
white = '#f1f1ef'

[colors]
draw_bold_text_with_bright_colors = true

[env]
#TERM = "alacritty"
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Monaco"
style = "Bold"

[font.bold_italic]
family = "Monaco"
style = "Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>\t'''

[window]
dynamic_padding = true

[window.dimensions]
columns = 111
lines = 30

[keyboard]
bindings = [
{ key= "F", mods= "Command", chars = "\u0006" },
{ key= "G", mods= "Command", chars = "\u0007" },
{ key= "V", mods= "Command", chars = "\u0016" },
{ key= "Insert", mods= "Shift", action = "PasteSelection" },
]
